name: Build, Deploy, and Upload Artifacts

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: petclinic-artifacts
        path: target/

    - name: Run Spring Boot application
      run: mvn spring-boot:run &
    
    - name: Wait for 1 minute
      run: sleep 60

    - name: Check application health
      run: |
        echo "Checking application health..."
        curl -s --head http://localhost:8080/actuator/health | head -n 10

    - name: Stop Spring Boot application
      run: mvn spring-boot:stop
